backend/IMS/urls.py
from django.db import router
from django.urls import path
from . import views
app_name = 'route'

urlpatterns = [
    path('logout/', views.logout, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('products/', views.products, name="products"),
    path('purchase/', views.purchase, name="purchase"),
    path('suppliers/', views.supplier, name="supplier"),
    path('invoice/', views.invoice, name="invoice"),
    path('', views.login, name="login"),
    path('generateInvoice/', views.generateInvoice, name="generateInvoice"),
    path('cancel', views.cancel, name="cancel"),
    path('save', views.save, name="save"),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('IMS.urls')),
    path('admin/', admin.site.urls),
]

backend/templates/Invoice.html
{% extends 'index.html' %} {% block content %}

<div class="formGenerate">
  <form action="{% url 'route:generateInvoice' %}" method="POST">
    {% csrf_token %}
    <input
      type="submit"
      value="Generate Invoice"
      class="add"
      style="width: 150px; height: 50px"
    />
  </form>
</div>

<!-- <div class="invoiceForm">
  <form method="POST" action = "{% url 'route:invoice' %}">
    {% csrf_token %}

    <div class="form-title">
      <p>Add Invoice</p>
    </div>
    <div class="input-list">
      <div class="input_field">
        <label for="price">Invoice ID:</label>
        {{ form.invoice_id }}
      </div> 
      <div class="input_field">
        <label for="price">Product ID:</label>
        {{ form.product_id }}
      </div>

      <div class="input_field">
        <label for="quantity">Quantity:</label>
        {{ form.ordered_quantity }}
      </div>

      <div class="input_field">
        <label for="supplier_ID">Price:</label>
        {{ form.line_total }}
      </div>
    </div>
    <div class="buttons">
      <input type="submit" value="Add" class="add" />
      <input type="button" value="Cancel" class="add" />
    </div>
  </form>
</div>
 -->

<div class="invoiceTable">
  <table id="example" class="table table-striped" style="width: 100%">
    <thead>
      <tr>
        <th>SN</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
      </tr>
    </thead>
    <tbody>
      {% for invoice in invoice_data %}
      <tr>
        <td>{{ invoice.invoice_id_id }}</td>
        <td>{{ invoice.product_id}}</td>
        <td>{{ invoice.ordered_quantity}}</td>
        <td>{{ invoice.line_total}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

{% endblock %}

backend/templates/generate_invoice.html
{% extends 'index.html' %} {% block content %}

<div class="invoiceForm">
  
  <form method="POST" action = "{% url 'route:invoice' %}">
    {% csrf_token %}

    <div class="form-title">
      <p>Add Invoice</p>
    </div>
    {% comment %} <div class="input-list">
      <div class="input_field">
        <label for="price">Invoice ID:</label>
        {{ form.invoice_id }}
      </div> {% endcomment %}
      <div class="input_field">
        <label for="price">Product ID:</label>
        {{ form.product_id }}
      </div>

      <div class="input_field">
        <label for="quantity">Quantity:</label>
        {{ form.ordered_quantity }}
      </div>

      <div class="input_field">
        <label for="supplier_ID">Price:</label>
        {{ form.line_total }}
      </div>
    </div>
    <div class="buttons">
      <input type="submit" value="Add" class="add" />
    </div>
  </form>
  <form action="{% url 'route:cancel' %}" method="post">
    {% csrf_token %}

    <input type="submit" value="Cancel" class="add" />
  </form>

  <form action="{% url 'route:save' %}" method="post">
    {% csrf_token %}

    <input type="submit" value="Save" class="add" />
  </form>
</div> 
{% endblock %}

backend/templates/index.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta informations of web page. -->
    <meta charset="UTF-8">
    <meta name="description" content="Home page of my portfolio">
    <meta name="keyword" content="portfolio, cv, blogs, html portfolio, css, html, javascript">
    <meta name="author" content="Anish Shrestha">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- External CSS and JS link.  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Adding Icon library to the webpage. -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" />
    
    <title>{{ title }}</title>
</head>

<body id="body">
    <!-- A navigation bar that slides from the right side of the web page. -->
    <aside class="sideBar" id="sideBar">
        <a href="javascript:void(0)" class="close" onclick="closeNav()">&times;</a>

        <ul class="sidebar-nav">
            <li class="nav-item">
                <a href="{% url 'route:dashboard' %}" class="nav-link">
                    <i class="fas fa-house"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'route:products' %}" class="nav-link">
                    <i class="fas fa-box"></i>
                    <span>Products</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'route:supplier' %}" class="nav-link">
                    <i class="fas fa-house-user"></i>
                    <span>Suppliers</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="pages/customers.html" class="nav-link">
                    <i class="fas fa-users"></i>
                    <span>Customers</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'route:purchase' %}" class="nav-link">
                    <i class="fas fa-dollar"></i>
                    <span>Purchase</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'route:invoice' %}" class="nav-link">
                    <i class="far fa-file-lines"></i>
                    <span>Invoice</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="pages/report.html" class="nav-link">
                    <i class="fas fa-chart-line"></i>
                    <span>Report</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="pages/help.html" class="nav-link">
                    <i class="fas fa-question"></i>
                    <span>Help</span>
                </a>
            </li>
        </ul>
    </aside>

    <!-- Parts of the webpage other than the side navigation bar.  -->

    <!-- Header of webpage.  -->

    <!-- An icon which when clicked on slides in the navigation bar.  -->
    <div class="openSideNav" id="openSideNav">
        <span
            style="font-size: 36px; display: inline; float: left; color:rgb(255, 255, 255); align-content: left; cursor: pointer; top: 0; margin: 0.6rem 0 0 1rem;"
            onclick="openNav()">&#9776;</span>

        <div class="user-menu">
            <div class="user" onclick="dropdown()">
                <div class="profile-image">
                    <img src="../images/1.jpg" alt="">
                </div>
            </div>
        </div>

    </div>

    <div id="dropdown" class="dropdown" style="display:none">
        <div class="user-intro">
            <div class="profile-image">
                <img src="../images/1.jpg" alt="">
            </div>

            <div class="user-info">
                <span>{{request.user}}</span>
            <p>lakhanthapa@gmail.com</p>
            </div>
        </div>
        
       <div class="edit-profile"> <i class="fas fa-pen"></i> Edit profile</div>

        <div class="profile-list">
            <ul>
                <li class="profile-menu">
                    <a href="accountSettings.html">
                        <i class="fas fa-user"></i>
                        <span>Account</span>
                    </a>
                </li>
    
                <!-- <li class="dropdown-menu">
                    <hr>
                </li>
     -->
                <li class="profile-menu">
                    <a href="accountSettings.html">
                        <i class="fas fa-cog"></i>
                        <span>Settings</span>
                    </a>
                </li>
    
                <!-- <li class="dropdown-menu">
                    <hr>
                </li> -->
    
                <li class="profile-menu">
                    <a href="../logout">
                        <i class="fas fa-sign-out"></i>
                        <span>Sign Out</span>
                    </a>
                </li>
            </ul>

        </div>

       
    </div>

    <div id="main"onclick="closeDropdown()">
        {% block content %}
        
        {% endblock %}
        
    </div>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

backend/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta informations of web page. -->
    <meta cFharset="UTF-8">
    <meta name="description" content="Home page of my portfolio">
    <meta name="keyword" content="portfolio, cv, blogs, html portfolio, css, html, javascript">
    <meta name="author" content="Anish Shrestha">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- External CSS and JS link.  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
    <!-- Adding Icon library to the webpage. -->
    <link rel="stylesheet"
        href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet"
        href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css' %}"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Login - IMS</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
    </style>

</head>

<body>
    <div class="main-container" id="blur">
        <div class="wrapper">
            <div class="title-text" id="signIn">
                <div class="title sign-in">Sign In</div>
            </div>

            <div class="title-text" id="signUp">
                <div class="title sign-in">Sign Up</div>
            </div>

            <div class="form-container" id="frontface">
                <div class="frontface" id="front">
                    <form action="" class="login" method="post">
                        {% csrf_token %}
                        <div class="field">
                            <input type="text" placeholder="Username" name="username" required>
                        </div>
                        <div class="field">
                            <input type="password" placeholder="Password" name="password" required>
                        </div>
                        {% for message in messages %}
                        <span class="errorMessage" style="color: red;
                            font-size: 13px; margin-top:5px;"> {{ message }} </span>
                        {% endfor %}
                        <div class="link">
                            <a href="#">Forgot password?</a>
                        </div>
                        <div class="field">
                            <input type="submit" value="Sign In">
                        </div>
                        <div class="signup-link">Not a member? <a href="#" onclick="signUp()">Signup now</a></div>
                    </form>
                </div>
            </div>
            <div class="backface" id="backface">
                <form action="" class="login" method="post">
                    {% csrf_token %}
                    <div class="field" id="names">
                        <input type="text" placeholder="First name" name="first_name" required
                            style="margin-right: 10px;">
                        <input type="text" placeholder="Last name" name="last_name" required>
                    </div>
                    <div class="field">
                        <input type="text" placeholder="Username" name="username" required>
                    </div>
                    <div class="field">
                        <input type="email" placeholder="Email" name="email" required>
                    </div>
                    <div class="field">
                        <input type="text" placeholder="Address" name="address" required>
                    </div>
                    <div class="field">
                        <input type="text" placeholder="Phone number" name="address" required>
                    </div>
                    <div class="field">
                        <input type="password" placeholder="Password" name="password" required>
                    </div>
                    <div class="field">
                        <input type="password" placeholder="Confirm Password" name="password" required>
                    </div>
                    <div class="field">
                        <input type="submit" value="Sign Up" onclick="toogle()">
                    </div>
                    <div class="signup-link">Already a member? <a href="#" onclick="signIn()">Signin</a></div>
                </form>
            </div>
        </div>
    </div>


</body>

</html>

backend/templates/products.html
{% extends 'index.html' %}

{% block content %}
<div class="table-container">
  <table id="example" class="table table-striped" style="width:100%">
    <thead>
      <tr>
        <th>SN</th>
        <th>Name</th>
        <th>Unit Price</th>
        <th>Quantity</th>
        <th>Supplier</th>

      </tr>
    </thead>
    <tbody>
      {% for product in data %}
      <tr>
        <td>{{ product.id }}</td>
        <td>{{ product.product_name }} </td>
        <td>{{ product.unit_price }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.supplier_id }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div id="addButton">
  <button class="add" onclick="addProduct()">
    <i class="fas fa-add"></i>
    <span>Add Product</span>
  </button>
</div>

<div id="product-form">
  <form method="POST">
    {% csrf_token %}
    <!-- {{ form.as_p }}
    <div class="add-button">
      <input type="submit" value="Add Product" class="add" />
      <input type="button" value="Cancel" class="add" onclick="closeAddMenu()" />
    </div> -->

    <span class="title">Add Product</span>
      <div class="add-field">
        <label for="name">Name:</label>
        {{ form.product_name }}
      </div>

      <div class="add-field">
        <label for="price">Unit Price:</label>
        {{ form.unit_price }}
      </div>

      <div class="add-field">
        <label for="supplier_ID">Supplier:</label>
        {{ form.supplier_id }}        
      </div>

      <div class="add-field">
        <label for="quantity">Quantity:</label>
        {{ form.quantity }}        
      </div>

      <div class="add-button">
        <input type="submit" value="Add Product" class="add" />
        <input type="button" value="Cancel" class="add" onclick="closeAddMenu()" />
      </div>
  </form>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

<script>
  // add form for product
  function addProduct() {
    document.getElementById("product-form").style.display = "flex";
    document.getElementById("example_wrapper").style.display = "none";
    document.getElementById("addButton").style.display = "none";
  }

  function closeAddMenu() {
    document.getElementById("product-form").style.display = "none";
    document.getElementById("addButton").style.display = "flex";
    document.getElementById("example_wrapper").style.display = "inline";
  }
</script>

{% endblock %}

backend/templates/purchase.html
{% extends 'index.html' %}

{% block content %}
<div class="table-container">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>SN</th>
          <th>Product ID</th>
          <th>Purchase Date</th>
          <th>Quantity</th>
          <th>Purchase Price</th>
        </tr>
      </thead>
      <tbody>
        {% for purchase in purchase_data %}
        <tr>
          <td>{{ purchase.id }}</td>
          <td>{{ purchase.product_id }}</td>
          <td>{{ purchase.purchase_date}}</td>
          <td>{{ purchase.quantity}} </td>
          <td>{{ purchase.purchase_price }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div id="addButton">
    <button class="add" onclick="addProduct()">
      <i class="fas fa-add"></i>
      <span>Add Purchase</span>
    </button>
  </div>
  
  <div id="product-form">
  
    <form method="POST">
      {% csrf_token %}
      <span class="title">Add Purchase</span>
        <div class="add-field">
          <label for="price">Product ID:</label>
          {{ form.product_id }}
        </div>
  
        <div class="add-field">
          <label for="supplier_ID">Price:</label>
          {{ form.purchase_price }}        
        </div>
  
        <div class="add-field">
          <label for="quantity">Quantity:</label>
          {{ form.quantity }}        
        </div>
  
        <div class="add-button">
          <input type="submit" value="Add Purchase" class="add" />
          <input type="button" value="Cancel" class="add" onclick="closeAddMenu()" />
        </div>
    </form>
  </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  
  <script>
    // add form for product
    function addProduct() {
      document.getElementById("product-form").style.display = "flex";
      document.getElementById("example_wrapper").style.display = "none";
      document.getElementById("addButton").style.display = "none";
    }
  
    function closeAddMenu() {
      document.getElementById("product-form").style.display = "none";
      document.getElementById("addButton").style.display = "flex";
      document.getElementById("example_wrapper").style.display = "inline";
    }
  </script>
  
{% endblock %}

backend/templates/supplier.html
{% extends 'index.html' %}

{% block content %}
<div class="table-container">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>SN</th>
          <th>Supplier ID</th>
          <th>Supplier number</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
        {% for supplier in supplier_data %}
        <tr>
          <td>{{ supplier.id }}</td>
          <td>{{ supplier.supplier_name }}</td>
          <td>{{ supplier.supplier_number}}</td>
          <td>{{ supplier.email}} </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div id="addButton">
    <button class="add" onclick="addProduct()">
      <i class="fas fa-add"></i>
      <span>Add Supplier</span>
    </button>
  </div>
  
  <div id="product-form">
  
    <form method="POST">
      {% csrf_token %}
      <span class="title">Add Purchase</span>
        <div class="add-field">
          <label for="price">Supplier name:</label>
          {{ form.supplier_name }}
        </div>
  
        <div class="add-field">
          <label for="supplier_ID">Supplier number:</label>
          {{ form.supplier_number}}        
        </div>
  
        <div class="add-field">
          <label for="quantity">Email:</label>
          {{ form.email }}        
        </div>
  
        <div class="add-button">
          <input type="submit" value="Add Supplier" class="add" />
          <input type="button" value="Cancel" class="add" onclick="closeAddMenu()" />
        </div>
    </form>
  </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  
  <script>
    // add form for product
    function addProduct() {
      document.getElementById("product-form").style.display = "flex";
      document.getElementById("example_wrapper").style.display = "none";
      document.getElementById("addButton").style.display = "none";
    }
  
    function closeAddMenu() {
      document.getElementById("product-form").style.display = "none";
      document.getElementById("addButton").style.display = "flex";
      document.getElementById("example_wrapper").style.display = "inline";
    }
  </script>
  
{% endblock %}